---
- name: Ensure Github plugin configuration
  template:
    src: "templates/integration/github/config.xml.j2"
    dest: "{{ jenkins_home }}/github-plugin-configuration.xml"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0440
  notify: restart jenkins
  become: true
