---
- name: Get Jenkins crumb
  uri:
    url: '{{ jenkins_uri }}/crumbIssuer/api/json'
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    force_basic_auth: yes
    return_content: yes
  register: jenkins_crumb
  when: jenkins_github_enabled and jenkins_github_token != ""

- name: Create Jenkins 'Secret Text' credentials
  uri:
    method: POST
    url: '{{ jenkins_uri }}/credentials/store/system/domain/_/createCredentials'
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    force_basic_auth: yes
    headers:
      Jenkins-Crumb: "{{ jenkins_crumb.json.crumb }}"
    body: |
      json={
        "": "0",
        "credentials": {
          "scope": "{{ item.scope | default('GLOBAL') }}",
          "id": "{{ item.id | default('') }}",
          "secret": "{{ item.secret }}",
          "description": "{{ item.name }}",
          "$class": "org.jenkinsci.plugins.plaincredentials.impl.StringCredentialsImpl"
        }
      }
    # Returns 302 when credential already exists
    status_code: 302,404
  register: result
  with_items: "{{ jenkins_credentials_secret_text }}"
