---
- name: Get Jenkins crumb
  uri:
    url: '{{ jenkins_uri }}/crumbIssuer/api/json'
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    force_basic_auth: yes
    return_content: yes
  register: jenkins_crumb
  when: |
    (jenkins_github_enabled and jenkins_github_token != "")
    or jenkins_credentials_ssh_private_keys | count > 0
    or jenkins_credentials_secret_text | count > 0

# Reference
#  - https://www.greenreedtech.com/creating-jenkins-credentials-via-the-rest-api/
#
- name: Create Jenkins 'SSH Private Key' credentials
  vars:
    create_ssh_private_key:
      scope: "{{ item.scope | default('GLOBAL') }}"
      id: "{{ item.id | default('') }}"
      description: "{{ item.name }}"
      username: "{{ item.username | default('') }}"
      passphrase: "{{ item.passphrase | default('') }}"
      privateKeySource:
        stapler-class: "com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey$DirectEntryPrivateKeySource"
        privateKey: "{{ item.privatekey }}"
      stapler-class: "com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey"
  uri:
    method: POST
    url: '{{ jenkins_uri }}/credentials/store/system/domain/_/createCredentials'
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    force_basic_auth: yes
    headers:
      Jenkins-Crumb: "{{ jenkins_crumb.json.crumb }}"
    body: |
      json={
        "": "0",
        "credentials": {{ create_ssh_private_key | to_json}}
      }
    # Returns 302 when credential already exists
    status_code: 302,404
  register: result
  with_items: "{{ jenkins_credentials_ssh_private_keys }}"
  when: jenkins_credentials_ssh_private_keys | count > 0
  no_log: false


- name: Create Jenkins 'Secret Text' credentials
  uri:
    method: POST
    url: '{{ jenkins_uri }}/credentials/store/system/domain/_/createCredentials'
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    force_basic_auth: yes
    headers:
      Jenkins-Crumb: "{{ jenkins_crumb.json.crumb }}"
    body: |
      json={
        "": "0",
        "credentials": {
          "scope": "{{ item.scope | default('GLOBAL') }}",
          "id": "{{ item.id | default('') }}",
          "secret": "{{ item.secret }}",
          "description": "{{ item.name }}",
          "$class": "org.jenkinsci.plugins.plaincredentials.impl.StringCredentialsImpl"
        }
      }
    # Returns 302 when credential already exists
    status_code: 302,404
  register: result
  with_items: "{{ jenkins_credentials_secret_text }}"
  when: jenkins_credentials_secret_text | count > 0
  no_log: true
