---

- name: Install distro packages
  package:
    name: "{{ jenkins_install_distro_packages }}"
    state: present
  become: true
  when: jenkins_install_distro_packages | count > 0

- name: Install pip packages
  pip:
    name: "{{ jenkins_install_pip_packages }}"
    state: present
  become: true
  when: jenkins_install_pip_packages | count > 0
