---

#
#
### CONFIG
#
- name: Configure Jenkins
  template:
    src: templates/jenkins/config.xml.j2
    dest: "{{ jenkins_home }}/config.xml"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0644
    backup: "yes"
  become: true
  notify: restart jenkins

- name: Configure Jenkins location
  template:
    src: templates/jenkins/location.xml.j2
    dest: "{{ jenkins_home }}/jenkins.model.JenkinsLocationConfiguration.xml"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0644
    backup: "yes"
  become: true
  notify: restart jenkins

- name: Configure Jenkins CLI
  template:
    src: templates/jenkins/cli.xml.j2
    dest: "{{ jenkins_home }}/jenkins.CLI.xml"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0644
    backup: "yes"
  become: true
  notify: restart jenkins

- name: Configure Jenkins Shell
  template:
    src: templates/jenkins/shell.xml.j2
    dest: "{{ jenkins_home }}/hudson.tasks.Shell.xml"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0644
    backup: "yes"
  become: true
  notify: restart jenkins


#
#
### TOOLS
#
- include: tools/git/initialise.yml

- include: tools/python/initialise.yml
  when: jenkins_python_enabled

- include: tools/ant/initialise.yml

- include: tools/nodejs/initialise.yml


#
#
### INTEGRATIONS
#
- include: integrations/github/initialise.yml


#
#
### ENVIRONMENTS
#
- include: environments/python.yml
  when: jenkins_env_python_enabled

- include: environments/docker.yml
  when: jenkins_env_docker_enabled

- include: environments/ansible-molecule.yml
  when: jenkins_env_molecule_enabled
