---
#
#
### VARIABLES
#
- name: Set jenkins URI
  set_fact:
    jenkins_uri: "http://{{
        jenkins_hostname ~ ':' ~ jenkins_http_port
        ~ (jenkins_url_prefix | ternary(
          '/' ~ jenkins_url_prefix,
          ''
        ))
      }}"

# jenkins_plugin module doesn't support password files.
- name: Get Jenkins admin password from file.
  slurp:
    src: "{{ jenkins_admin_password_file }}"
  register: adminpasswordfile
  no_log: true
  when: jenkins_admin_password_file != ""

- name: Set Jenkins admin password fact.
  set_fact:
    jenkins_admin_password: "{{ adminpasswordfile['stdout']
      | default(jenkins_admin_password) }}"
  no_log: true


#
#
### CONFIG
#
- name: Ensure Jenkins secret key
  copy:
    dest: "{{ jenkins_home }}/{{ item.path }}"
    content: "{{ item.secret }}"
    mode: 0640
    owner: "{{ jenkins_owner }}"
    group: "{{ jenkins_group }}"
    force: false
  become: true
  notify: restart jenkins
  when: item.secret | default(false, true) != false
  with_items:
    - { secret: "{{ jenkins_secret_key }}", path: secret.key }

- name: Configure Jenkins
  template:
    src: templates/jenkins/config.xml.j2
    dest: "{{ jenkins_home }}/config.xml"
    owner: "{{ jenkins_owner }}"
    group: "{{ jenkins_group }}"
    mode: 0644
    backup: "yes"
  become: true
  notify: restart jenkins

- name: Configure Jenkins location
  template:
    src: templates/jenkins/location.xml.j2
    dest: "{{ jenkins_home }}/jenkins.model.JenkinsLocationConfiguration.xml"
    owner: "{{ jenkins_owner }}"
    group: "{{ jenkins_group }}"
    mode: 0644
    backup: "yes"
  become: true
  notify: restart jenkins

- name: Configure Jenkins CLI
  template:
    src: templates/jenkins/cli.xml.j2
    dest: "{{ jenkins_home }}/jenkins.CLI.xml"
    owner: "{{ jenkins_owner }}"
    group: "{{ jenkins_group }}"
    mode: 0644
    backup: "yes"
  become: true
  notify: restart jenkins

- name: Configure Jenkins Shell
  template:
    src: templates/jenkins/shell.xml.j2
    dest: "{{ jenkins_home }}/hudson.tasks.Shell.xml"
    owner: "{{ jenkins_owner }}"
    group: "{{ jenkins_group }}"
    mode: 0644
    backup: "yes"
  become: true
  notify: restart jenkins


#
#
### TOOLS
#
- include: tools/git/initialise.yml

- include: tools/ant/initialise.yml

- include: tools/nodejs/initialise.yml


#
#
### INTEGRATIONS
#
- include: integrations/github/initialise.yml
