---

- name: Import RedHat vars
  include_vars: vars/redhat_package_vars.yml
  when: ansible_os_family == 'RedHat'

- name: Import Debian vars
  include_vars: vars/debian_package_vars.yml
  when: ansible_os_family == 'Debian'

- name: Initialise
  include: initialise.yml

- name: Install dependencies
  include: dependencies.yml

- name: Setup Jenkins
  include: setup.yml
  when: jenkins_farm_role == 'master'

- name: Setup Jenkins farm
  include: farm/setup.yml
  when: jenkins_farm_enabled
