---

- name: Initialise
  include: initialise.yml

- name: Install dependencies
  include: dependencies.yml

- name: Setup Jenkins
  include: setup.yml
  when: jenkins_farm_role == 'master'

- name: Setup Jenkins farm
  include: farm/setup.yml
  when: jenkins_farm_enabled
