---

- name: Manage plugins
  include: install-plugins.yml

- name: Ensure credentials
  include: credentials.yml

- name: Manage Git tools
  include: tools/git/configure.yml

- name: Manage Apache ant tools
  include: tools/ant/configure.yml
  when: jenkins_ant_installations

- name: Manage nodeJS tools
  include: tools/nodejs/configure.yml
  when: jenkins_nodejs_installations

- name: Configure github
  include: integrations/github/configure.yml
  when: jenkins_github_enabled
