---
- name: Ensure nodeJS tool configuration file
  template:
    src: "templates/tools/nodejs/config.xml.j2"
    dest: "{{ jenkins_home }}/jenkins.plugins.nodejs.tools.NodeJSInstallation.xml"
    owner: "{{ jenkins_owner }}"
    group: "{{ jenkins_group }}"
    mode: 0440
  notify: restart jenkins
  become: true
