---
- name: Do we need to install the nodeJS plugin?
  set_fact:
    jenkins_config_plugins: "{{ jenkins_config_plugins 
      + [{'name':'nodejs'}]
      }}"
  when: "jenkins_nodejs_installations
    and (
      jenkins_config_plugins | json_query('[?name==`nodejs`].name')
    ) | count == 0"
