---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: yaml-lint.yml
platforms:
  - name: "${MOLECULE_JENKINS_NAME:-debian9}"
    image: "${MOLECULE_JENKINS_IMAGE:-dankempster/debian-jenkins-ansible:9-0.4}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: ${ARJC_TESTENV_PRIVILEGED:-true}
    pre_build_image: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: configured
  test_sequence:
    # - lint
    - destroy
    # - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    # - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  options:
    junit-xml: ${MOLECULE_BUILD_REPORTS:-../../build/reports}/${MOLECULE_JENKINS_NAME:-debian9}-testinfra-configured.junit.xml
  env:
    TARGET_HOST: "${MOLECULE_JENKINS_NAME:-debian9}"
  lint:
    name: flake8
