---
- name: Converge
  hosts: all
  become: true
  vars_files:
    - vars/main.yml

  pre_tasks:
    - include_tasks: java-8.yml

  roles:
    - role: geerlingguy.git
      become: true

    - role: geerlingguy.java
      become: true

    - role: geerlingguy.jenkins
      become: true

    - role: ../../../

  post_tasks:
    - name: Check if Jenkins is running.
      uri:
        url: "http://127.0.0.1:8080/"
      retries: "{{ jenkins_connection_retries }}"
      delay: "{{ jenkins_connection_delay }}"
