---
- name: Converge
  hosts: all
  vars_files:
    - vars/main.yml

  roles:
    - role: ansible-role-jenkins-config

  post_tasks:
    - name: Check if Jenkins is running.
      uri:
        url: "http://127.0.0.1:8080/"
