---
- name: Converge
  hosts: all
  become: true
  vars_files:
    - vars/main.yml

  pre_tasks:
    - include_tasks: java-8.yml
      when: ansible_architecture != 'armv7l'

  roles:
    - role: geerlingguy.git
      become: true

    - role: ../../../
