---
- hosts: all
  vars_files:
    - vars/main.yml

  roles:
    - role: geerlingguy.git
      become: true

    - role: geerlingguy.java
      become: true

    - role: geerlingguy.jenkins
      become: true
