---
- name: Ensure the git-client plugin will be installed
  set_fact:
    jenkins_config_plugins: "{{ jenkins_config_plugins | default([], true)
      + [{'name':'git-client'}]
      }}"
  when: "jenkins_git_installations | count > 0
    and 'git-client' not in jenkins_config_plugins
    and (
      (jenkins_config_plugins | json_query('[?name==`git-client`].name'))
      | default([], true)
    ) | count == 0"
