---

- include: ../../tools/git/client.yml

- name: Do we need to install the Git plugin?
  set_fact:
    jenkins_config_plugins: "{{ jenkins_config_plugins
      + [{'name':'git'}]
      }}"
  when: "jenkins_git_installations | count > 0
    and (
      jenkins_config_plugins | json_query('[?name==`git`].name')
    ) | count == 0"
