---

- name: Do we need to install the Git plugin?
  set_fact:
    jenkins_config_plugins: "{{ jenkins_config_plugins
      + [{'name':'git'}]
      }}"
  when: "'git' not in jenkins_config_plugins
    and (
      (jenkins_config_plugins | json_query('[?name==`git-client`].name'))
      | default([], true)
    ) | count == 0"
