---
- name: Ensure Apache Ant tool configuration file
  template:
    src: "templates/tools/Ant/config.xml.j2"
    dest: "{{ jenkins_home }}/hudson.tasks.Ant.xml"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0440
  notify: restart jenkins
  become: true
